services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .backend/temp/imgs:/app/output_imgs
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  default:
    driver: bridge